---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:

  - name: Create a new host or update an existing host's info
    local_action:
      module: zabbix_host
      server_url: http://monitor.example.com
      login_user: username
      login_password: password
      host_name: ExampleHost
      status: disabled
      state: present
      inventory_mode: automatic
      proxy: a.zabbix.proxy
